server:
  port: 8080

spring:
  profiles:
    active: dev

    management:
      endpoints:
        web:
          exposure:
            include: "*"
---

spring:
  profiles: dev
  datasource:
    username: admin
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: admin
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  profiles: qa
  datasource:
    username: admin
    url: jdbc:h2:mem:testdb-qa
    driverClassName: org.h2.Driver
    password: admin
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  profiles: prod
  datasource:
    username: admin
    url: jdbc:h2:mem:testdb-prod
    driverClassName: org.h2.Driver
    password: admin
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
